// Application release metadata and version control configuration
export interface AppVersionInfo {
  version: string;
  buildNumber: string;
  author: string;
  releaseDate: string;
  codename: string;
  changelog: string[];
}

export const CURRENT_APP_VERSION: AppVersionInfo = {
  version: '2.31.1',
  buildNumber: '20260825-R31',
  author: 'NJ',
  releaseDate: '2026-08-25',
  codename: 'Category 19 & 20 50-Term Diagnostic Schematic Customization',
  changelog: [
    'v2.31.1: Implemented 50 dedicated, distinct CAD Diagnostic Schematics for all newly added terms in Category 19 (#411~#430: Always-on-Top Pin, Dockable Panel, Resize Grips, Opacity Slider, Split Pane Divider, Magnetic Snap Zone, Roll-Up, Floating Action Ribbon, Focus Dimmer, Multi-Doc Grid, Context Nested Flyout, Radial Pie Menu, Mnemonic Underline, Recent Files, Hamburger Drawer, Floating Inspector, Taskbar Peek, System Status Bar, Snap Layouts, Crash Recovery Banner) and Category 20 (#441~#470: Marquee Selection, Momentum Inertia Pan, Drag Threshold Deadzone, Auto-Scroll Boundary, Hover Intent Timer, Safe Triangle Hover, Triple-Click Select, Long-Press Trigger, Pinch-to-Zoom, Touch Rotate, Swipe Dismiss, Pull-to-Refresh, Middle-Click Auto-Scroll, Magnetic Button Proximity, Magnifier Loupe, Crosshair Laser, Snap to Grid, Anchor Connection Snap, Signature Scratchpad, Dial Knob, Dual Range Slider, Color Eyedropper, Cursor Ripple Wave, Parallax Tilt, Spotlight Torch, Trail Particle, Image Zoom Lens, File Drop Overlay, Before/After Slider, Lasso Selection). 100% verified without generic fallbacks.',
    'v2.31.0: Complete overhaul and visual elevation of the "DIAGNOSTIC SCHEMATIC" suite. Transformed basic wireframe boxes into professional CAD Blueprint Architecture viewports equipped with precision 10px/50px tick rulers, coordinate crosshairs (X/Y, Zoom scale), live alignment indicators, and dynamic dimension markers. Integrated full interactive controls into TermDetailModal (Blueprint / Dark CAD / Slate theme switcher, Guides & Dimensions toggle, 1.0x/1.25x/1.5x zoom inspector, and Component Anatomy Breakdown matrix). Verified WCAG AA contrast and 100% build integrity across all 640 UI/UX master terms.',
    'v2.30.0: Full construction and integration of 50 advanced terms (#411~#430 in Category 19 Window & Menu Bars and #441~#470 in Category 20 Mouse & Pointer Controls). Built 50 dedicated 1:1 Live UX components with full interactivity (Always-On-Top Pin, Dockable Panel, Window Resize Grips, Window Opacity Slider, Split Pane Divider, Magnetic Snap Zone, Window Roll-Up/Shade, Floating Action Ribbon, Window Focus Dimmer, Multi-Document Grid, Context Nested Flyout, Radial Pie Menu, Menu Mnemonic Underline, Recent Files Menu, Hamburger Drawer Menu, Floating Inspector Palette, Taskbar Thumbnail Peek, System Status Bar, Snap Layouts Selector, Crash Recovery Banner, Pointer Lock FPS, Momentum Inertia Scroll Physics, Elastic Rubber Banding, Magnetic Cursor Snapping, Custom Cursor Trail, Stylus Pressure Sensitivity, Hover Scrub Timeline, Pinch/Spread Zoom, 2-Finger Rotation, Long-Press Haptic Wave, Direct Canvas Spatial Pan, Snap to Guide Grid, Smart Distribute Guides, 3-Finger Swipe History, Touch Hit Expansion, Wheel Shift Horizontal, Custom Drag Ghost Preview, Right-Click Orbit 3D Camera, Double-Click Header Maximize, Triple-Click Paragraph Select, Drag Auto-Scroll Edge, Click Ripple Shockwave, Bezier Tangent Handles, Freeform Lasso Select, 300ms Hover Tooltip Delay, Hover Card Rich Flyout, Click Outside Backdrop Dismiss, Right-Drag Measurement Ruler, Drag Reorder Placeholder, Spatial Compass Minimap HUD). Reconciled all imports/exports and synchronized total database count to 640 items.',
    'v2.29.1: Rebranded all live interactive component sandbox views across the platform from "LIVE INTERACTIVE LAB" to "Live UX". Resolved dispatch precedence in LiveDemoRenderer.tsx so Term #640 (Search Bar with Advanced Filter Dropdown) renders its dedicated search options popover panel immediately rather than being intercepted by the generic search input. Replaced trash icon with clear (X) in basic search and verified filter icon toggle (SlidersHorizontal/Filter) to reveal all advanced search fields (Sender, Recipient, Subject, Keywords, Size, Date, Scope, Attachments, Chat exclusion, Filter rule creator).',
    'v2.29.0: Registered Term #640 (Search Bar with Advanced Filter Dropdown / 상세 검색 필터 드롭다운형 검색창) in Category 01 (Basic Inputs). Implemented dedicated 1:1 Live UX with Gmail-style search options popover panel (From, To, Subject, Has words, Excludes words, Size comparison, Date within range, Scope selector, Has attachment checkbox, Search / Reset / Create Filter actions) with active search query generator. Added distinct diagnostic schematic with full light/dark theme support and verified total count (640 terms).',
    'v2.28.0: Registered Term #639 (Draggable Inline Edit Row with Action Toolbar / 드래그 순서변경 인라인 편집 행) in Category 01 (Basic Inputs). Implemented dedicated 1:1 Live Interactive Lab with real-time byte counter (7/30byte), confirm (✓), cancel/revert (↺), delete (🗑), hover highlight row styling, and HTML5 drag-and-drop / direction reordering. Added distinct diagnostic schematic with full light/dark theme support and verified total count (639 terms).',
    'v2.27.0: Registered Term #637 (Document Tab Bar / Browser Tab Strip) and Term #638 (Omnibar with Breadcrumb Search / Explorer Address-Search Bar) in Category 03 (Navigation & Menus). Implemented dedicated 1:1 Live Interactive Labs in LiveNavLabs.tsx and high-contrast Diagnostic Schematics in TermSchematic.tsx with full light/dark theme parity and verified all counts (638 terms).',
    'v2.26.0: Full audit and complete 1:1 overhaul of Category 23 (Text Hint & Placeholder #551-#590) and Category 24 (Overlay & Transparency #591-#636). Created dedicated interactive lab modules /src/components/LiveTextHintLabs.tsx and /src/components/LiveOverlayTransparencyLabs.tsx, fully wired to LiveDemoRenderer.tsx without fallbacks. Verified 100% type safety and logged architectural diagnosis in log.md.',
    'v2.25.0: Full audit and complete 1:1 overhaul of Category 22 (Icons & Symbols #511-#550) with 40 dedicated interactive labs in LiveIconSymbolLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Action Icons, Status Icons, Kebab ⋮, Meatball …, Hamburger ☰, Grip Dots ⠿, Chevron vs Arrow, File Types, Bento Grid, Sort Indicators, Active Filters, Search 🔍, Clear ✕, Password Eye, External Link ↗, Copy 📋, Download ⬇, Upload ⬆, Locks, Bookmarks, Notification Bell, Settings Gear, Help ?, Info ℹ, Warning ⚠, Error ⛔, Success ✓, Spinner ◌, Undo/Redo, Trash 🗑, Edit ✎, Add ➕, Folders, Sync, Maximize/Minimize, Play/Pause, Tags, Avatars, aria-label). Conducted re-diagnosis on Category 21 (Keyboard Shortcuts #471-#510) and confirmed 100% 1:1 mapped integrity in log.md.',
    'v2.24.0: Full audit and complete 1:1 overhaul of Category 21 (Keyboard Shortcuts & Hotkeys #471-#510) with 40 dedicated interactive labs in LiveKeyboardShortcutLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Global Shortcuts Ctrl+S/Z, Modifier Keys Ctrl/Shift/Alt/Meta, Key Chord sequences, Arrow Key Nudge 1px/10px, Focus Trap modal tab loop, Escape to Dismiss, Shortcut Cheat Sheet, <kbd> 3D Badge, Conflict Resolution, Typeahead list jump, Access Key Alt+Mnemonic, Global Hotkey Listener, Scoped Shortcuts, Customizer, Spacebar Pan, Delete Selection, Duplicate Ctrl+D, Group/Ungroup, Select All, Invert Selection, Find Ctrl+F, Replace Modal, Command Palette Ctrl+K, Zoom In/Out/Fit/100%, Tab Navigation & Close/Reopen, Panel Toggles Sidebar/Console, Lock/Hide Selection, Align/Distribute Shortcuts, Fullscreen, Refresh, Accessibility Mode). Also completed deep architectural diagnosis of Category 22 (Icons & Symbols #511-#550).',
    'v2.23.0: Full audit and complete 1:1 overhaul of Category 20 (Mouse & Pointer Controls #431-#440) with 10 dedicated interactive labs in LiveMousePointerLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Pointer Hover State micro-interaction and glow, Pointer Active/Press State depth compression, Double-Click Action 2-click rename trigger, Right-Click Context Menu interceptor with duplicate/delete actions, Middle-Click Scroll/Pan wheel button stage pan, Mouse Wheel Zoom 50-250% scale, Cursor: Crosshair CAD precision wiring mode, Cursor: Grab/Grabbing hand tool toggle, Cursor: Col/Row Resize pane split divider, Pointer Capture setPointerCapture continuous off-screen drag tracking). Also completed deep architectural diagnosis of Category 21 (Keyboard Shortcuts & Hotkeys #471-#510).',
    'v2.22.0: Full audit and complete 1:1 overhaul of Category 19 (Window, Dialog & Menu Bars #391-#410) with 20 dedicated interactive labs in LiveWindowMenuLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Window Title Bar draggable handle, Window Control Buttons minimize/maximize/close, Menu Bar classic File/Edit/View strip, Drop-Down Menu Item with shortcut hints, Menu Separator 1px divider, Submenu cascading flyout, Checked Menu Item toggle checkmark, Radio Menu Item single choice, Disabled Menu Item dimmed state, Modal Window blocking backdrop, Modeless Dialog non-blocking floating search tool, Backdrop Click Dismiss overlay, Floating Palette Window top Z-index toolbox, Window Snapping magnetic edge alignment, Window Minimize taskbar collapse, Window Maximize/Restore full-viewport sizing, Cascade Windows diagonal stacking, Tile Windows 50:50 non-overlapping tile, Bring to Front active window focus, Sticky Notes Window pastel memo). Also completed full re-diagnosis and verification of Category 18 (Textbox · Memo & Text Editing #361-#390).',
    'v2.21.0: Full audit and complete 1:1 overhaul of Category 18 (Textbox · Memo & Text Editing #361-#390) with 30 dedicated interactive labs in LiveTextEditorLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Single-Line Text Box enter submit commit, Multi-Line Text Box 4-line log memo, Auto-Growing Textarea dynamic height expansion, Fixed-Height Textarea 70px scroll lock, Resizable Textarea bottom-right drag grip, Inline Text Editor 1-click title switcher, Contenteditable Field rich HTML block, Floating Text Box canvas sticky note, Anchored Text Box +14.2mm pin callout, Viewport-Fixed Text Box top-right HUD, Draggable Text Box canvas floating card, Resizable Text Box 2D bounding frame, Editable Overlay Label CAD dimension inline editor, Text Box Handle rotation knob transform box, Text Overflow CSS clip truncation, Text Wrapping break-words word boundaries, No-Wrap Text strict single line nowrap, Ellipsis (...) filename trailing marker, Expandable Text read more / show less toggle, Read-Only Text Field non-editable copyable token, Disabled Text Field 100% dimmed locked input, Prefix / Suffix Field https:// and :8080 addons, Physical Unit Input mm/cm/inch selector, Masked Text Input guided business license mask, Monospace Text Field code memory layout, Searchable Text Box real-time matching suggestions, Debounced Text Input 400ms delayed query trigger, Text Selection Toolbar floating format bubble ribbon, WYSIWYG Rich Text Editor bold/italic styling, Markdown Editor 2-pane split preview).',
    'v2.20.0: Full audit and complete 1:1 overhaul of Category 17 (Table · Grid · High-Capacity Data Processing #331-#360) with 30 dedicated interactive labs in LiveDataGridLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Editable Data Grid inline edit, Spreadsheet Grid Excel fx formula bar, Cell Editor dynamic type-picker, Cell Renderer graphical gauges/badges, Row Selection single/multi highlight, Cell Range Selection bounding box, Multi-Row Selection batch checkbox counter, Pinned Column left freeze, Pinned Row bottom total anchor, Sticky Table Header persistent th, Multi-Level Header 2-tier composite matrix, Grouped Column thermal cluster, Column Visibility hide/show toggle, Column Chooser checklist picker, Column Pinning header pin action, Column Autosize 1-click fit, Fit Columns to View 100% viewport fill, Row Height Auto dynamic multiline stretch, Dense Table 24px high-density, Comfortable Table 48px touch-friendly, Zebra Striping alternating stripes, Hover Row mouse highlight, Active Cell 2px blue focus outline, Dirty Cell orange modified marker, Validation Cell red error warning, Computed Column Qty*Price live calculation, Aggregate Row SUM/AVG statistical summary, Group Row category collapsible partition, Row Detail expandable sub-table, Inline Row Actions edit/clone/delete quick buttons).',
    'v2.19.0: Full audit and complete 1:1 overhaul of Category 16 (Layout Frame & Panes #301-#330) with 30 dedicated interactive labs in LiveLayoutFrameLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Application Shell global scaffold, App Frame desktop OS window chrome, Master-Detail live synchronized list-details, Two-Pane 50/50 split, Three-Pane IDE 3-column standard, Split View variable drag splitter, Nested Split Pane horizontal-vertical matrix, Dockable Panel pin/float toggle, Docking Layout 4-way cross compass, Collapsible Sidebar 0px slide collapse, Resizable Sidebar 80-200px drag handle, Inspector Panel contextual object details, Properties Panel key-value form, Utility Panel layers/history deck, Workspace Region central stage, Content Region route-driven body, Header Region top anchor, Footer Region ground metadata, Status Bar real-time diagnostic strip, Toolbar Region persistent tool row, Context Toolbar selection-triggered bar, Panel Stack shared footprint tabs, Panel Group accordion cluster, Responsive Split desktop row to mobile col, Min/Max Constraint clamped boundaries, Collapse Threshold auto snap-to-zero, Sticky Workspace Header pinned during scroll, Independent Scroll isolated dual overflows, Synchronized Scroll 1:1 linked offsets, Scroll Boundary overscroll containment). Also completed regression audit on Category 01 Basic Inputs (#001-#020) with 100% schematic and live lab coverage.',
    'v2.18.0: Full audit and complete 1:1 overhaul of Category 15 (Accessibility, System & Advanced Patterns #281-#300) with 20 dedicated interactive labs in LiveSystemLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Focus Ring 2px high-visibility offset ring, Keyboard Navigation arrow/tab indexed grid, Tab Order explicit 1-2-3-4 traversal sequence, Skip Link top jump shortcut, ARIA Label button descriptor, Screen Reader Text .sr-only accessible narration, High Contrast 19.5:1 AAA black-yellow mode, Dark Mode Slate #18202A palette, Light Mode Off-white #F8FAFC crisp daylight deck, Theme multi-preset color switcher, Design Token CSS variables architecture, Component modular Lego block, Variant CVA style permutations, Finite State Machine Idle-Running-Done transitions, Responsive Breakpoint sm/md/xl viewport simulator, Lazy Loading on-demand bundle splitting, DOM Virtualization 5 visible nodes / 100k records, Optimistic UI 0ms instant reaction with background sync, Undo/Redo Past-Present-Future history stacks, Command Bar contextual multi-item action ribbon).',
    'v2.17.0: Full audit and complete 1:1 overhaul of Category 14 (Forms, Validation & Data Entry #261-#280) with 20 dedicated interactive labs in LiveFormLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Form complete validated container, Form Group 4-in-1 atomic stack, Fieldset semantic perimeter, Legend boundary title, Label htmlFor focus binding, Helper Text ambient guide, Placeholder transient ghost, Required Field red asterisk with blocking validation, Optional Field non-blocking tag, Schema Validation Zod rules, Client-side Validation 0ms browser RegEx, Server-side Validation 409 DB conflict check, Inline Error attached alert, Input Mask 000-0000-0000 format, Character Counter real-time length limit, Clear Button 1-click reset, Form Reset rollback all inputs, Dirty State unsaved changes tracker, Autosave debounced persistence, Draft State interim vs published status).',
    'v2.16.0: Full audit and complete 1:1 overhaul of Category 13 (Canvas, Nodes & Diagramming #241-#260) with 20 dedicated interactive labs in LiveCanvasLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Canvas 2D infinite workspace surface, Workspace 3-pane diagram IDE, Node execution vertex with I/O ports, Edge dynamic Bezier connection wire, Connector elastic link tool, Port circular terminal hub, Anchor Point rotation origin +, Control Point Bezier tangent lever, Transform Handles 8-point matrix, Bounding Box dashed boundary, Selection Box active focus outline, Marquee Selection dragged rectangle, Lasso Selection freehand organic loop, Grid 20px dot matrix, Ruler pixel calibrated edge, Custom Guide cyan line, Smart Guide red center-snap auto guide, Alignment tools, Distribution 24px equal spacing, Auto Layout Dagre graph auto-routing).',
    'v2.15.0: Full audit and complete 1:1 overhaul of Category 12 (Timeline, Charts & Visualization #221-#240) with 20 dedicated interactive labs in LiveTimelineLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Timeline multi-track sequence, Gantt Chart with FS dependency links, Time Axis graduated scale, Time Scale 1x/2x/4x dynamic factor, Timeline Header sticky bar, Timeline Row 40px track lane, Timeline Bar duration clip, Playhead vertical needle scrubber, Time Cursor real-time tooltip, Marker event trigger flag, Milestone diamond gate symbol, Guide Line vertical projection, Grid Line 50ms interval grid, Major Tick labeled marks, Minor Tick 20ms subdivisions, Zoom Control 50%-300%, Zoom to Fit auto calculation, Range Selection loop segment, Brush overview sub-chart slider, Mini Map radar viewport thumbnail).',
    'v2.14.0: Full audit and complete 1:1 overhaul of Category 11 (Drag, Drop & Direct Manipulation #201-#220) with 20 dedicated interactive labs in LiveDnDLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Drag & Drop Queue Transfer, Draggable cursor grab, Droppable target container, Drop Zone CAD file upload, Drag Handle isolated 6-dot grip, Grab Handle title bar move, Textured Splitter Grip, Drop Indicator 2px line with target notch, Drag Preview rotating follower, Ghost Element origin silhouette, Expanding Placeholder, Snap alignment guide, Discrete Snap Points, 20px Modular Snap Grid, Magnetic Snap auto-coupling, Free Drag 1px mode, Direct Resize duration handle, Direct Move offset shifter, Canvas Viewport Pan hand tool, Marquee Rubber Band multi-selection).',
    'v2.13.0: Full audit and complete 1:1 overhaul of Category 10 (States & Interaction #181-#200) with 20 dedicated interactive labs in LiveStateLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Default/Normal, Hover, Focus Ring, Active Pressed, Selected, Disabled, Read-only Copyable, Checked, Unchecked, Indeterminate 3-State, Expanded, Collapsed, Loading Async Lock, Error Invalid, Warning Caution, Success Valid, Pressed Aria-Pressed Toggle, Dragged 50% Opacity, Drop Target Zone, Focus-Visible Keyboard Ring). Verified WCAG AA contrast across light and dark modes.',
    'v2.12.0: Full audit and complete 1:1 overhaul of Category 09 (Feedback & Status #161-#180) with 20 dedicated interactive labs in LiveFeedbackLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Alert Banner, Toast, Snackbar with Undo, Notification Center, Badge, Status Indicator, Status Dot, Progress Bar, Progress Ring, Spinner, Skeleton, Empty State, Error State, Success State, Warning State, Info State, Callout, Inline Validation, Error Message, Success Message). Refactored LiveDemoRenderer and TermSchematic containers to deliver WCAG AA compliant contrast in both Light and Dark mode.',
    'v2.11.0: Full audit and complete 1:1 overhaul of Category 08 (Dialogs, Popups & Overlays #141-#160) with 20 dedicated interactive labs in LiveDialogLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx (Modal, Dialog, Alert Dialog, Confirmation Dialog, Popover, Popup, Tooltip, Contextual Popover, Drawer Overlay, Backdrop, Scrim, Lightbox, Sheet, Bottom Sheet, Side Sheet, Anchored Popup, Non-modal Dialog, Fullscreen Modal, Inline Dialog, Coachmark).',
    'v2.10.0: Full audit and complete 1:1 overhaul of Category 07 (Disclosure & Hierarchy #121-#140) with 20 dedicated interactive labs in LiveDisclosureLabs.tsx and distinct high-contrast diagnostic schematics in TermSchematic.tsx.',
    'v2.9.0: Full audit and complete 1:1 overhaul of Category 03 (Navigation & Menus #041-#060) with 20 dedicated interactive labs in LiveNavLabs.tsx. Recorded strict mandatory 1:1 verification rule in log.md.',
    'v2.8.0: Full overhaul of Category 06 (Tables & Data Grids #101-#120) with 20 dedicated interactive labs and high-contrast diagnostic schematics.',
    'v2.7.0: Full overhaul of Category 05 (Scrolling, Positioning & Virtualization #081-#100) with 20 dedicated interactive labs and high-contrast schematics.',
    'v2.6.0: Full overhaul of Category 04 (Layout & Containers #061-#080) with 20 dedicated interactive labs and high-contrast schematics. Added Fast Preview Jump Bar for immediate live testing.',
    'v2.5.0: Upgraded Diagnostic Schematic typography/contrast for high readability. Fully revamped Category 01 (#009-#018) with dedicated, typing-enabled, differentiated Live Labs.',
    'v2.4.0: Added Header Collapse/Expand toggle, Version metadata & export manifest, by NJ branding badge, dynamic total terms count synchronization.',
    'v2.3.0: Sticky Top Header & Global Search Bar with independent scroll containment.',
    'v2.2.0: Comprehensive Live Interactive Lab overhaul across all 24 categories with distinct functional sandboxes.',
    'v2.1.0: Enhanced search bar with clear button and Lucide icons.',
    'v2.0.0: Full 24-category UI/UX Encyclopedia with interactive schematics.',
  ],
};
